### ISSUE TITLE
Mode 73 colours?

### ISSUE THREAD

**Issue by mikefairbank** [soruk42/MatrixBrandy#1]
How many colours should mode 73 have?  The document https://github.com/soruk42/MatrixBrandy/blob/master/docs/ScreenModes.txt says 4, but it seems there are many more.

**Comment by mikefairbank** [comment]
I meant to post this to the stardot/matrixbrandy repository.

**Comment by soruk42** [comment]
Not a problem, this is my "own" copy - it's mirrored rather than forked. Anyway, the doc was WAY out of date, so just pushed an update. The definitive screen mode information will always be in src/scrcommon.h
